import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";

/**
 * "Closing soon" deadlines box, fed by /closing-soon.json — a static file
 * generated by `npm run alerts` (tools/deadline-alerts) and committed to
 * frontend/public/. Renders nothing if the file is missing, empty, or stale.
 */
const TYPE_ICONS = {
  "abstract":     "📝",
  "early-bird":   "💷",
  "registration": "🎟️",
  "hotel":        "🏨",
  "scholarship":  "🎓",
  "other":        "📌",
};

const DeadlinesWidget = ({ limit = 5 }) => {
  const [deadlines, setDeadlines] = useState(null);

  useEffect(() => {
    // Skip during react-snap prerender: days-left values are computed from the
    // visitor's clock, so baking them into static HTML would show stale
    // urgency and cause a hydration mismatch.
    if (typeof navigator !== "undefined" && navigator.userAgent === "ReactSnap") return;
    fetch("/closing-soon.json")
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (!data || !Array.isArray(data.deadlines)) return;
        // Re-derive days left from today so a stale file doesn't show wrong urgency;
        // drop anything already past.
        const today = new Date(new Date().toISOString().slice(0, 10) + "T00:00:00Z");
        const live = data.deadlines
          .map((d) => ({
            ...d,
            daysLeft: Math.round((new Date(d.date + "T00:00:00Z") - today) / 86400000),
          }))
          .filter((d) => d.daysLeft >= 0)
          .sort((a, b) => a.daysLeft - b.daysLeft);
        if (live.length > 0) setDeadlines(live);
      })
      .catch(() => {});
  }, []);

  if (!deadlines) return null;

  return (
    <section className="bg-amber-50 border border-amber-200 rounded-xl p-6">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-base font-semibold text-gray-900">⏰ Deadlines closing soon</h2>
        <Link to="/cpd" className="text-xs font-medium text-blue-600 hover:text-blue-800">
          All conferences →
        </Link>
      </div>
      <ul className="space-y-2.5">
        {deadlines.slice(0, limit).map((d) => (
          <li key={`${d.id}-${d.type}-${d.date}`} className="flex items-start gap-2.5 text-sm">
            <span className="flex-shrink-0">{TYPE_ICONS[d.type] || TYPE_ICONS.other}</span>
            <span className="min-w-0 text-gray-700">
              {d.url ? (
                <a href={d.url} target="_blank" rel="noopener noreferrer" className="font-medium text-gray-900 hover:text-blue-700 hover:underline">
                  {d.conference}
                </a>
              ) : (
                <span className="font-medium text-gray-900">{d.conference}</span>
              )}
              {" — "}{d.label}
            </span>
            <span
              className={`ml-auto flex-shrink-0 px-2 py-0.5 rounded-full text-xs font-semibold ${
                d.daysLeft <= 7 ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-800"
              }`}
            >
              {d.daysLeft === 0 ? "today" : `${d.daysLeft}d left`}
            </span>
          </li>
        ))}
      </ul>
    </section>
  );
};

export default DeadlinesWidget;
