import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { buildICS, downloadICS } from "../ics";

/**
 * "Closing soon" deadlines box, fed by /closing-soon.json — a static file
 * generated by `npm run alerts` (tools/deadline-alerts) and committed to
 * frontend/public/. Renders nothing if the file is missing, empty, or stale.
 */

// Export the live deadlines as all-day .ics events. Dates here are ISO
// (YYYY-MM-DD) from the deadline-alerts pipeline, so no parsing ambiguity.
const exportDeadlines = (deadlines) => {
  downloadICS(
    "vetnextstep-deadlines.ics",
    buildICS(deadlines.map((d) => {
      const [y, m, day] = d.date.split("-").map(Number);
      return {
        uid: `${d.id}-${d.type}-${d.date}`,
        summary: `${d.conference} — ${d.label}`,
        start: [y, m, day],
        end: [y, m, day],
        url: d.url,
        description: d.note,
      };
    }))
  );
};

const DeadlinesWidget = ({ limit = 5 }) => {
  const [deadlines, setDeadlines] = useState(null);

  useEffect(() => {
    // Skip during react-snap prerender: days-left values are computed from the
    // visitor's clock, so baking them into static HTML would show stale
    // urgency and cause a hydration mismatch.
    if (typeof navigator !== "undefined" && navigator.userAgent === "ReactSnap") return;
    fetch("/closing-soon.json")
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (!data || !Array.isArray(data.deadlines)) return;
        // Re-derive days left from today so a stale file doesn't show wrong urgency;
        // drop anything already past.
        const today = new Date(new Date().toISOString().slice(0, 10) + "T00:00:00Z");
        const live = data.deadlines
          .map((d) => ({
            ...d,
            daysLeft: Math.round((new Date(d.date + "T00:00:00Z") - today) / 86400000),
          }))
          .filter((d) => d.daysLeft >= 0)
          .sort((a, b) => a.daysLeft - b.daysLeft);
        if (live.length > 0) setDeadlines(live);
      })
      .catch(() => {});
  }, []);

  if (!deadlines) return null;

  return (
    <section className="bg-[#fdf7e7] border border-gray-200 border-l-4 border-l-notice">
      <div className="flex items-baseline justify-between gap-4 px-4 pt-3.5">
        <h2 className="text-sm font-bold text-gray-900">Deadlines closing soon</h2>
        <Link to="/cpd" className="text-xs text-blue-800 underline underline-offset-2">All conferences</Link>
      </div>
      <ul className="px-4 pt-2 pb-1">
        {deadlines.slice(0, limit).map((d) => (
          <li
            key={`${d.id}-${d.type}-${d.date}`}
            className="flex items-baseline justify-between gap-3 py-1.5 text-sm border-b border-dotted border-[#ded3b4] last:border-b-0"
          >
            <span className="min-w-0 text-gray-700">
              {d.url ? (
                <a href={d.url} target="_blank" rel="noopener noreferrer" className="font-semibold text-gray-900 underline underline-offset-2 decoration-gray-300 hover:decoration-gray-900">
                  {d.conference}
                </a>
              ) : (
                <span className="font-semibold text-gray-900">{d.conference}</span>
              )}
              {" — "}{d.label}
            </span>
            <span
              className={`flex-shrink-0 text-xs tabular-nums ${
                d.daysLeft <= 7 ? "font-bold text-red-800" : "font-semibold text-notice"
              }`}
            >
              {d.daysLeft === 0 ? "today" : `${d.daysLeft} days`}
            </span>
          </li>
        ))}
      </ul>
      <button
        onClick={() => exportDeadlines(deadlines)}
        className="mx-4 mb-3.5 text-xs text-notice underline underline-offset-2 hover:text-gray-900"
        title="Download these deadlines as an .ics file for your calendar"
      >
        Add these deadlines to your calendar (.ics)
      </button>
    </section>
  );
};

export default DeadlinesWidget;
